### ISSUE TITLE
pypi is still at 0.15.0 

### ISSUE THREAD

**Issue by larseggert** [nodejs/gyp-next#242] opened 2024-04-23 08:41 UTC
https://pypi.org/project/gyp-next/

Closed by #234

**Comment by cclauss** [comment] 2024-04-23 09:07
Duplicate of
* #234

@ryzokuken

**Comment by ryzokuken** [comment] 2024-04-25 12:32
@cclauss thanks for the ping, I responded to #234

**Comment by cclauss** [comment] 2024-04-30 12:39
Now at v0.17.0

**Closed by cclauss** 2024-04-30 12:39 UTC
