### ISSUE TITLE
gyp-next on pypi.org is out of date by 2 years

### ISSUE THREAD

**Issue by mozkeeler** [nodejs/gyp-next#161] opened 2022-08-17 19:16 UTC
https://pypi.org/project/gyp-next/ only has gyp-next 0.4.0, which is about 2 years old at this point. It would be great to have the more recent releases available there.

**Comment by gengjiawen** [comment] 2022-08-26 15:43
duplicate of https://github.com/nodejs/gyp-next/issues/29.

**Closed by gengjiawen** 2022-08-26 15:43 UTC
